import type { Metadata } from "next";
import { Geist, Roboto } from "next/font/google";
import "@/styles/colors.css";
import "./globals.css";
import { type ReactNode } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>): ReactNode {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${geistSans.variable}`}>
        {children}
      </body>
    </html>
  );
}
